export default {
  LogoAccountScreen: require('../assets/logo/adiogent-logo.png'),
  SplashScreen: require('../assets/adiogent_splash.png'),
  AccountProfileImage: require('../assets/user_profile.png'),
  NotFoundResult: require('../assets/productnotfound.gif'),
  EmptyCart: require('../assets/emptybox.gif'),
  OrderNotFound: require('../assets/no-orders.gif'),
  noProductImage: require('../assets/no-image.png'),
  OrderCompleted: require('../assets/ordercomplete.gif'),
  Logo: require('../assets/logo/appicon.png'),
  instagram: require('../assets/social/instagram.png'),
  facebook: require('../assets/social/facebook.png'),
  youtube: require('../assets/social/youtube.png'),
  linkedin: require('../assets/social/linkedin.png'),
  twitter: require('../assets/social/twitter.png'),
  whatsapp: require('../assets/social/whatsapp.png'),
  telegram: require('../assets/social/telegram.png'),
  startRecordingGif: require('../assets/start-recording.gif'),
  listeningRecordingGif: require('../assets/listening-recording.gif'),
  ratingsImg: require('../assets/ratings.png'),
  refer_earn_screen:require("../assets/refer_earn_screen.png"),
  redeem_coins_screen:require("../assets/redeem_coins_screen.png"),

  dollar: require('../assets/dollar.png'),
  refer: require('../assets/refer.png'),
  share: require('../assets/share.png'),
  moneybag: require('../assets/money-bag.png'),
  signup: require('../assets/signup.png'),

  number_1: require('../assets/number-1.png'),
  number_2: require('../assets/number-2.png'),
  number_3: require('../assets/number-3.png'),
  party: require('../assets/party.png'),
};
